# Generated by Django 4.0.3 on 2022-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemasList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('domain_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SchemasList',
                'verbose_name_plural': 'SchemasList',
            },
        ),
    ]
